export const quizQuestions = [
  {
    q: 'What is the capital of France?',
    a: 'Berlin',
    b: 'Madrid',
    c: 'Paris',
    correct: 'c',
  },
  {
    q: 'Which planet is known as the Red Planet?',
    a: 'Venus',
    b: 'Mars',
    c: 'Jupiter',
    correct: 'b',
  },
  {
    q: 'What is the largest mammal in the world?',
    a: 'Elephant',
    b: 'Blue Whale',
    c: 'Giraffe',
    correct: 'b',
  },
  {
    q: 'How many continents are there on Earth?',
    a: '5',
    b: '6',
    c: '7',
    correct: 'c',
  },
  {
    q: 'What is the main ingredient in guacamole?',
    a: 'Tomato',
    b: 'Avocado',
    c: 'Onion',
    correct: 'b',
  },
  {
    q: 'In which year did the first manned moon landing occur?',
    a: '1969',
    b: '1975',
    c: '1982',
    correct: 'a',
  },
  {
    q: 'Which country is famous for its tulips?',
    a: 'Netherlands',
    b: 'Italy',
    c: 'Japan',
    correct: 'a',
  },
  {
    q: 'What is the capital of Japan?',
    a: 'Seoul',
    b: 'Beijing',
    c: 'Tokyo',
    correct: 'c',
  },
  {
    q: 'How many colors are there in a rainbow?',
    a: '5',
    b: '7',
    c: '10',
    correct: 'b',
  },
  {
    q: 'What is the largest ocean on Earth?',
    a: 'Atlantic Ocean',
    b: 'Indian Ocean',
    c: 'Pacific Ocean',
    correct: 'c',
  },
  {
    q: 'Which animal is known as the "King of the Jungle"?',
    a: 'Lion',
    b: 'Tiger',
    c: 'Leopard',
    correct: 'a',
  },
  {
    q: 'What is the square root of 64?',
    a: '6',
    b: '8',
    c: '10',
    correct: 'b',
  },
  {
    q: 'Which is the largest planet in our solar system?',
    a: 'Mars',
    b: 'Jupiter',
    c: 'Saturn',
    correct: 'b',
  },
  {
    q: 'What is the capital of Australia?',
    a: 'Sydney',
    b: 'Melbourne',
    c: 'Canberra',
    correct: 'c',
  },
  {
    q: 'How many sides does a hexagon have?',
    a: '5',
    b: '6',
    c: '7',
    correct: 'b',
  },
];
